export enum ErrorCode {
    SUCCESS = 'SUCCESS',
    SERVER_ERROR = 'SERVER_ERROR',
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
    FORBIDDEN = 'FORBIDDEN',
    REQUEST_FAILED = 'REQUEST_FAILED',
    BAD_REQUEST = 'BAD_REQUEST',
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  }